### ISSUE TITLE
Doc updates for mitaka release

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv1#114]
#### OpenStack Release
Mitaka

#### Description
Make the necessary updates for the Mitaka release:
- supported features
- unsupported features
- set up docs/conf.py to use package version number automatically like in [f5-common-python](https://github.com/F5Networks/f5-common-python/blob/0.1/docs/conf.py)

**Comment by mattgreene** [comment]
This is a duplicate bug (which has been closed).
