### ISSUE TITLE
Unable to activate BIG-IP license for VE deployed on Ubuntu KVM hypervisor

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-lbaasv1#32]
#### Agent Version
2.0.1

#### Operating System
Ubuntu 14.04

#### OpenStack Release
Liberty

#### Description
The hypervisor presents a BIOS string that is incompatible with the F5 license server.

#### Deployment
OpenStack compute node running Ubuntu with a KVM hypervisor.

#### Workaround
Change  /usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py to include the lines in bold below and restart nova-compute:

<pre><code>
def _configure_guest_by_virt_type(self, guest, virt_type, caps, instance,
                                  image_meta, flavor, root_device_name):
    if virt_type == "xen":
        if guest.os_type == vm_mode.HVM:
            guest.os_loader = CONF.libvirt.xen_hvmloader_path
    elif virt_type in ("kvm", "qemu"):
        if caps.host.cpu.arch in (arch.I686, arch.X86_64):
            guest.sysinfo = self._get_guest_config_sysinfo(instance)
            guest.os_smbios = vconfig.LibvirtConfigGuestSMBIOS()
            <b>guest.sysinfo.bios_vendor = "SeaBIOS"</b>
            <b>guest.sysinfo.bios_version = "foo"</b>
</code></pre>

**Comment by gitrick22** [comment]
This issue has been resolved on the F5 licensing server.
