### ISSUE TITLE
Update README build section for all artifacts and architectures

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-openstack-lbaasv1#5]
Make sure that the [README](../README.rst) file contains the build instructions for building all the artifacts on the supported build machines.  It appears that the previous `make` command no longer is working in Ubuntu.

I believe the combinations are
* `.deb` on Ubuntu
* `.deb` with Docker
* `.rpm` on Ubuntu
* `.rpm` with Docker
* `.tgz` on Ubuntu (this would contain both target packages)
* `.tgz` with Docker (this would contain both target packages)

This fix should go into the `1.0` branch and then be merged to master.

**Comment by jputrino** [comment]
Also, the name of the repo in the README needs correction (lbaas instead of lbass).
