### ISSUE TITLE
config sync issue between f5 pairs when running F5 Agents in HA ?

### ISSUE THREAD

**Issue by mahanhi** [F5Networks/f5-openstack-lbaasv1#65]
* Title: Will there be any impact when I run multiple Agents in HA for the same F5 pair we see Config sync issue between F5 pairs, the status says "Changes Pending"

#### Agent Version
1.0.1

#### Operating System
Ubuntu 14.04

#### OpenStack Release
Kilo

#### Description
Will there be any impact when I run multiple Agents in HA for the same F5 pair we see Config sync issue between F5 pairs, the status says "Changes Pending", does running F5 Agent in HA one in each controller will cause this ?

#### Deployment
 Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance (in Pair)

**Comment by mattgreene** [comment]
There is config sync bug present in 1.0.10, that is resolved in 1.0.12.  Please see issue #33.

We've also observed that the horizon dashboard doesn't refresh automatically.  I have seen cases frequently when clicking on the apply button in horizon where status immediately updates to "Changes Pending".  Try forcing a page reload in the browser after a few seconds and see if the status updates again.

**Comment by mattgreene** [comment]
Closing this 'question' as there has been no additional inquiry or discussion since Mar 4.  Please create a new issue if you require more information.
